# Generated by Django 5.1.4 on 2025-01-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "qid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("que", models.TextField()),
                ("classTh", models.IntegerField(max_length=4)),
                ("a", models.CharField(max_length=255)),
                ("b", models.CharField(max_length=255)),
                ("c", models.CharField(max_length=255)),
                ("d", models.CharField(max_length=255)),
                ("ans", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=30)),
                ("classTh", models.IntegerField(max_length=4)),
                ("email", models.EmailField(max_length=50)),
                ("mobileNo", models.IntegerField(max_length=11)),
                ("test_attempted", models.IntegerField(default=0)),
                ("points", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "resultid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("time", models.TimeField(auto_now=True)),
                ("attempt", models.IntegerField()),
                ("right", models.IntegerField()),
                ("worng", models.IntegerField()),
                ("points", models.FloatField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="GWG.user"
                    ),
                ),
            ],
        ),
    ]
